device: "cuda"
model:
  type: "deeplabv3plus" # unet or deeplabv3
  n_classes: 19
  backbone: "resnet"
data:
  root: "data"
  image_size: [512, 1024] # height, width
  augment: true
  ignore_index: 255
training:
  epochs: 20
  lr: 2e-4  # 降低学习率
  weight_decay: 5e-4  # 增加权重衰减
  batch_size: 4
  k_folds: 3
  early_stopping_patience: 8  # 增加早停耐心值
  lr_schedule: "cosine"  # 使用余弦退火学习率调度
  loss: "combined"  # 使用组合损失函数
output:
  base_dir: "outputs"
  save_checkpoints: true
  save_best_only: false
